//kubernetes Service file 

apiVersion: v1
kind: Service
metadata:
  name: nodelabexamsvc
  labels:
    app: nodelabexamsvc
spec:
  selector:
    matchLabels:
      app: nodelabexam
  ports:
  -port: 34
   targetPort: 3000
  type: NodePort
