//kubernetes Service file 

apiVersion: v1
kind: Service
metadata:
  name: "Nodelabexamsvc"
  labels:
    app: nodelabexamsvc
spec:
  selector:
    matchLabel:
      app: nodelabexam
  ports:
  -port: 34
   targetport: 3000
  type: NodePort
